// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:71be8918-f339-45ce-bd94-4e694c638820",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_fFqyns0fs",
    "aws_user_pools_web_client_id": "56golfugcqpbu89oh7bcqljgmu",
    "aws_user_files_s3_bucket": "memepin-images",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
